myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.home, name='home'),
]

sendmail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.core.mail import send_mail


def home(request):
    if request.method=='POST':
        message_name = request.POST['name']
        message_email = request.POST['email']
        message = request.POST['message']

        send_mail(
            'New Message!',
            f'Message from: {message_name}\nEmail: {message_email}\n\n{message}',
            message_email,
            [''],
        )

        return render(request, 'success.html', {'message_name': message_name})
    
    else:
        return render(request, 'home.html')

def success(request):
    return render(request, 'success.html')

myapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <title>Sending Mails</title>
</head>
<body>
    <h1 class="text-center">Sending emails with Django!</h1>
    <form method="POST" action="" class="m-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Name:</label><br />
            <input type="text" id="name" name="name" class="form-control"><br />
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email:</label><br />
            <input type="text" id="email" name="email" class="form-control"><br />
        </div>

        <div class="mb-3">
        <label for="message" class="form-label">Message:</label><br />
        <textarea type="text" id="message" name="message" class="form-control" style="height: 100px;"></textarea> <br />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
</html>

myapp/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <title>Sending Mails</title>
</head>
<body>
    <h1 class="text-center">Sending emails with Django!</h1>
    <div class="container m-5 gap-2">
        <h2>{{ message_name }}, your message has been sent!</h2>
        <a href="{% url 'myapp:home' %}"><button class="btn btn-primary m-2">send another email</button></a>
    </div>
</body>
</html>